# fly.toml app configuration file generated for steamspy on 2023-08-11T00:09:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "steamspy"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
